spring:
  security:
    jwt:
      expiracao: 30
      chave-assinatura: mvpservicoFacil@gmail.com
  servicos:
      address: https://receitaws.com.br/
      url: v1/cnpj/{cnpj}
  mail:
    host: smtp.gmail.com
    port: 587
    username: mvpservicoFacil@gmail.com
    password: pfciklosdotbgpgs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  main:
    allow-circular-references: true
  data:
    mongodb:
      uri: mongodb+srv://mvpservicofacil:AwQsSKn5l7pACxRv@cluster0.brnhojy.mongodb.net/
      database: usuario
